version: "3.8"

services:
  app:
    image: ghcr.io/casiimir/online-rep-monitoring-inference:latest
    container_name: online-rep-monitoring-app
    ports:
      - "8000:8000"  # API
      - "8001:8001"  # metrics
    # Se la tua immagine è privata, ricordati di fare "docker login ghcr.io" prima di avviare

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - app

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
